version: '3.4'

services:
  cmscore.content.api:
    image: ${DOCKER_REGISTRY}cmscorecontentapi
    build:
      context: .
      dockerfile: CMSCore.Content.Api\Dockerfile

  cmscore.content.client:
    image: ${DOCKER_REGISTRY}cmscorecontentclient
    build:
      context: .
      dockerfile: CMSCore.Content.Client\Dockerfile


  cmscore.content.silo:
    image: ${DOCKER_REGISTRY}cmscorecontentsilo
    build:
      context: .
      dockerfile: CMSCore.Content.Silo\Dockerfile

